---
lang: "pt"
listing:
  - id: equipe
    contents: "Equipe/Atual/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 3
    fields: [image, title, subtitle]
    grid-item-align: center
    sort: sortby
#  - id: ex
#    contents: "Equipe/Antigos/*.qmd"
#    type: table
#    sort: "nome desc"
#    sort-ui: [title]
#    fields: [title, end]
#    field-display-names: 
#      title: "Nome"
#      end: "Categoria"
---



<center>
<h2>
Interessado(a) em fazer parte do projeto?
</h2>
</center>

O projeto está desenhado para trabalharmos com 8 alunos da graduação e 5 alunos da pós-graduação e entre as atividades a serem realizadas pelos envolvidos temos:

-   Manutenção do Website e alimentação das redes sociais
-   Organização dos Meetup online
-   Elaboração de conteúdo para o blog
-   Elaboração dos tutoriais
-   Elaboração de minicursos (1 por semestre)
-   Elaboração de material para divulgação

> As reuniões de coordenação e planejamento semanal acontecerão sextas-feiras às 9:00 da manhã.


::: {.justify}
Além de aprender e ensinar uma nova linguagem de programação com grande potencial na academia e na indústria, o projeto contribui para uma sociedade mais envolvida com a tecnologia, promovendo a equidade de gênero, raça e condição social nas áreas de STEM e disciplinas relacionadas. Os alunos envolvidos também terão a oportunidade de desenvolver suas habilidades de comunicação oral e escrita, _soft skills_ essenciais para o mundo atual.
:::



<center>
Interessado(a) em fazer parte do projeto? Entre em contato via email com o coordenador do projeto, Prof. Carlos Trucíos.
</center>




## Equipe

::: {#equipe}
:::




